name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Xvfb and run it
      run: |
        sudo apt-get update -y
        sudo apt-get install -y xvfb
        Xvfb :1 -screen 0 1024x768x16 &
        export DISPLAY=:1
        echo "Xvfb 설치 및 실행 완료"

    - name: Run tests or your application
      run: |
        # 여기에 Streamlit 앱 실행 코드 또는 테스트 코드를 추가
        streamlit run app.py
